<?php

// http://www.huygens-fokker.org/docs/modename.html

// numbers in the array are stacked intervals, ie the intervals above the previous

$scales = array(

array(array(2, 10), 	array('Vietnamese ditonic')),
array(array(5, 7), 	array('Honchoshi: Japan')),
array(array(7, 5), 	array('Niagari: Japan')),
array(array(10, 2), 	array('Warao ditonic: South America')),
array(array(3, 2, 7), 	array('Vietnamese tritonic')),
array(array(3, 4, 5), 	array('Ute tritonic, Peruvian tritonic 2')),
array(array(4, 3, 5), 	array('Raga Malasri, Peruvian tritonic 1')),
array(array(4, 5, 3), 	array('Raga Bilwadala')),
array(array(5, 2, 5), 	array('Raga Sarvasri, Warao tritonic: South America')),
array(array(5, 5, 2), 	array('Sansagari: Japan')),
array(array(6, 1, 5), 	array('Raga Ongkari')),
array(array(1, 5, 1, 5), 	array('Messiaen truncated mode 5')),
array(array(5, 1, 5, 1), 	array('Messiaen truncated mode 5 inverse')),
array(array(2, 4, 2, 4), 	array('Messiaen truncated mode 6')),
array(array(4, 2, 4, 2), 	array('Messiaen truncated mode 6 inverse')),
array(array(1, 4, 3, 4), 	array('Raga Lavangi, Gowleeswari')),
array(array(2, 1, 7, 2), 	array('Warao tetratonic: South America')),
array(array(2, 2, 3, 5), 	array('Eskimo tetratonic (Alaska: Bethel)')),
array(array(3, 2, 2, 5), 	array('Vietnamese tetratonic')),
array(array(2, 3, 2, 5), 	array('Genus primum')),
array(array(2, 3, 3, 4), 	array('Raga Haripriya')),
array(array(2, 3, 4, 3), 	array('Raga Bhavani')),
array(array(2, 4, 5, 1), 	array('Raga Sumukam')),
array(array(4, 2, 5, 1), 	array('Raga Nigamagamini')),
array(array(4, 3, 3, 2), 	array('Raga Mahathi', 'Antara Kaishiaki')),
array(array(3, 4, 3, 2), 	array('Bi Yu: China')),
array(array(5, 2, 3, 2), 	array('Genus primum inverse')),
array(array(2, 3, 2, 1, 4), 	array('Han-kumoi: Japan, Raga Shobhavari, Sutradhari')),
array(array(2, 1, 4, 1, 4), 	array('Aeolian Pentatonic', 'Hira-joshi', 'Kata-kumoi', 'Yona Nuki Minor: Japan', 'Tizita Minor (Half tizita): Ethiopia')),
array(array(1, 4, 2, 1, 4), 	array('Hon-kumoi-joshi', 'Sakura', 'Akebono II: Japan', 'Olympos Enharmonic', 'Raga Salanganata', 'Saveri', 'Gunakri (Gunakali)', 'Latantapriya', 'Ambassel: Ethiopia'),
array(array(1, 4, 2, 3, 2), 	array('Kokin-joshi', 'Miyakobushi', 'Han-Iwato', 'In Sen: Japan', 'Raga Vibhavari (Revati)', 'Bairagi, Lasaki')),
array(array(1, 4, 1, 4, 2), 	array('Iwato: Japan')),
array(array(2, 3, 2, 2, 3), 	array('Scottish Pentatonic', 'Blues Major', 'Ritusen', 'Ritsu (Gagaku): Japan', 'Zhi', 'Zheng: China', 'Ujo', 'P\'yongjo: Korea', 'Bac: Vietnam', 'Lai Soutsanaen', 'Lai Po Sai', 'Lai Soi: Laos', 'Raga Devakriya, Durga, Suddha Saveri, Arabhi, Major complement'),
array(array(2, 2, 3, 2, 3), 	array('Major Pentatonic, Ryosen, Yona Nuki Major: Japan, Man Jue, Gong: China, Raga Bhopali (Bhup), Mohanam, Deskar, Bilahari, Kokila, Jait Kalyan, Peruvian Pentatonic 1, Ghana Pentatonic 2, Tizita Major: Ethiopia'),
array(array(2, 3, 2, 3, 2), 	array('Suspended Pentatonic, Raga Madhyamavati, Madhmat Sarang, Megh, Egyptian, Shang, Rui Bin, Jin Yu, Qing Yu: China, Yo: Japan, Ngu Cung Dao: Vietnam, Yematebela wofe: Ethiopia'),
array(array(2, 3, 3, 2, 2), 	array('Chaio: China')),
array(array(2, 2, 2, 3, 3), 	array('Kung: China')),
array(array(1, 4, 2, 2, 3), 	array('Altered Pentatonic', 'Raga Manaranjani II')),
array(array(2, 1, 2, 4, 3), 	array('Raga Abhogi')),
array(array(4, 2, 1, 4, 1), 	array('Lydian Pentatonic', 'Raga Amritavarshini', 'Malashri', 'Shilangi', 'Batti Lydian: Ethiopia')),
array(array(2, 1, 2, 3, 4), 	array('Raga Audav Tukhari')),
array(array(4, 1, 4, 2, 1), 	array('Raga Bhinna Shadja', 'Kaushikdhvani, Hindolita')),
array(array(1, 2, 4, 1, 4), 	array('Phrygian Pentatonic', 'Balinese Pelog', 'Madenda Modern', 'Raga Bhupalam', 'Bhupala Todi', 'Bibhas')),
array(array(2, 2, 3, 1, 4), 	array('Raga Bhupeshwari', 'Janasammodini')),
array(array(2, 2, 1, 2, 5), 	array('Raga Budhamanohari')),
array(array(3, 2, 4, 2, 1), 	array('Raga Chandrakauns (modern)', 'Marga Hindola', 'Rajeshwari')),
array(array(3, 2, 4, 1, 2), 	array('Raga Chandrakauns (Kafi)', 'Surya', 'Varamu')),
array(array(3, 2, 3, 3, 1), 	array('Raga Chandrakauns (Kiravani)')),
array(array(1, 2, 3, 2, 4), 	array('Raga Chhaya Todi', 'Locrian Pentatonic 1')),
array(array(1, 2, 2, 3, 4), 	array('Raga Chitthakarshini')),
array(array(2, 3, 2, 4, 1), 	array('Raga Desh', 'Tcherepnin Major Pentatonic', 'Nam xuan: Vietnam')),
array(array(1, 6, 1, 3, 1), 	array('Raga Deshgaur')),
array(array(5, 2, 1, 3, 1), 	array('Raga Devaranjani (Devaranji)')),
array(array(3, 2, 2, 3, 2), 	array('Minor Pentatonic, Blues Pentatonic, Raga Dhani (Suddha Dhanyasi), Abheri, Udhayaravi Chandrika, Qing Shang, Gu Xian, Jia Zhong, Yu: China, P\'yongjo-kyemyonjo: Korea, Minyo: Japan, Lai Yai, Lai Noi: Laos, Nam, Northern Sa mac: Vietnam, Peruvian Pentatonic 2, Batti Minor: Ethiopia'),
array(array(4, 2, 1, 2, 3), 	array('Raga Dhavalashri')),
array(array(4, 1, 2, 4, 1), 	array('Ionian Pentatonic, Raga Gambhiranata, Pelog Degung Modern, Ryukyu: Japan, Vong co: Vietnam, Batti Major: Ethiopia')),
array(array(1, 4, 2, 4, 1), 	array('Raga Gauri')),
array(array(4, 1, 3, 3, 1), 	array('Raga Girija, Bacovia: Romania, Batti Major sharp 5: Ethiopia')),
array(array(2, 3, 4, 1, 2), 	array('Raga Guhamanohari')),
array(array(2, 2, 3, 4, 1), 	array('Raga Hamsadhvani (Hansdhwani, Haunsadhwani)')),
array(array(3, 3, 2, 2, 2), 	array('Raga Harikauns, Chin: China')),
array(array(4, 2, 3, 2, 1), 	array('Raga Hindol (Sunada Vinodini), Sanjh ka Hindol')),
array(array(3, 2, 1, 4, 2), 	array('Raga Jayakauns')),
array(array(4, 1, 4, 1, 2), 	array('Raga Khamaji Durga')),
array(array(3, 2, 2, 1, 4), 	array('Raga Kokil Pancham')),
array(array(1, 4, 3, 3, 1), 	array('Raga Kshanika')),
array(array(1, 1, 6, 3, 1), 	array('Raga Kumarapriya')),
array(array(2, 2, 2, 5, 1), 	array('Raga Kumurdaki (Kumudki)')),
array(array(5, 2, 2, 1, 2), 	array('Raga Kuntvarali (Kuntalavarali)')),
array(array(3, 2, 3, 2, 2), 	array('Blues Minor, Raga Malkauns (Malakosh), Raga Hindola, Man Gong, Quan Ming, Yi Ze, Jiao: China, Shegaye: Ethiopia')),
array(array(4, 3, 2, 2, 1), 	array('Raga Mamata')),
array(array(1, 3, 3, 3, 2), 	array('Raga Manaranjani I')),
array(array(2, 5, 2, 1, 2), 	array('Raga Matha Kokila (Matkokil)')),
array(array(1, 3, 1, 3, 4), 	array('Raga Megharanjani, Syrian Pentatonic')),
array(array(1, 3, 1, 6, 1), 	array('Raga Megharanji')),
array(array(3, 1, 3, 2, 3), 	array('Raga Mohanangi')),
array(array(3, 3, 1, 4, 1), 	array('Raga Multani, Batti mineur')),
array(array(1, 1, 4, 1, 5), 	array('Raga Nabhomani')),
array(array(4, 1, 2, 2, 3), 	array('Raga Nagasvaravali, Raga Mand')),
array(array(3, 2, 2, 4, 1), 	array('Raga Nata, Udayaravicandrika, Madhuranjani')),
array(array(2, 2, 5, 2, 1), 	array('Raga Neroshta')),
array(array(2, 3, 3, 3, 1), 	array('Raga Priyadharshini')),
array(array(2, 1, 2, 2, 5), 	array('Raga Purnalalita, Chad Gadyo: Jewish, Ghana Pentatonic 1, Nando-kyemyonjo: Korea')),
array(array(5, 2, 2, 2, 1), 	array('Raga Puruhutika, Purvaholika')),
array(array(1, 1, 6, 1, 3), 	array('Raga Putrika')),
array(array(1, 3, 3, 2, 3), 	array('Raga Rasika Ranjani, Vibhas (Marva), Scriabin')),
array(array(2, 3, 4, 2, 1), 	array('Raga Rasranjani')),
array(array(1, 3, 3, 1, 4), 	array('Raga Reva, Revagupti, Ramkali, Vibhas (Bhairava)')),
array(array(1, 2, 4, 3, 2), 	array('Raga Rukmangi')),
array(array(3, 3, 1, 3, 2), 	array('Raga Samudhra Priya, Madhukauns (pentatonic)')),
array(array(1, 5, 1, 1, 4), 	array('Raga Saugandhini, Yashranjani')),
array(array(2, 1, 4, 2, 3), 	array('Dorian Pentatonic, Raga Sivaranjini (Shivranjani), Akebono I: Japan')),
array(array(3, 4, 1, 2, 2), 	array('Raga Shailaja, Varini')),
array(array(2, 4, 1, 2, 3), 	array('Raga Shri Kalyan')),
array(array(2, 4, 3, 2, 1), 	array('Raga Shubravarni')),
array(array(2, 4, 1, 4, 1), 	array('Raga Vaijayanti, Hamsanada')),
array(array(4, 3, 2, 1, 2), 	array('Raga Valaji')),
array(array(4, 1, 2, 1, 4), 	array('Raga Zilaf')),
array(array(2, 2, 3, 3, 2), 	array('Dominant Pentatonic')),
array(array(4, 1, 2, 3, 2), 	array('Mixolydian Pentatonic, Nam ai, Oan: Vietnam, Raga Savethri')),
array(array(3, 1, 2, 4, 2), 	array('Locrian Pentatonic 2')),
array(array(3, 2, 2, 2, 3), 	array('Minor added sixth Pentatonic, Kyemyonjo: Korea')),
array(array(2, 2, 2, 2, 2, 2), 	array('Whole-tone, Messiaen mode 1, Raga Gopriya, Anhemitonic Hexatonic')),
array(array(2, 3, 2, 2, 1, 2), 	array('Mixolydian Hexatonic, P\'yongjo: Korea, Yosen: Japan, Raga Darbar, Narayani, Suposhini, Andolika, Gorakh Kalyan')),
array(array(2, 2, 2, 3, 1, 2), 	array('Prometheus (Scriabin), Mystic, Raga Barbara)')),
array(array(1, 3, 2, 3, 1, 2), 	array('Prometheus Neapolitan')),
array(array(3, 2, 1, 1, 3, 2), 	array('Blues scale I, Raga Nileshwari)')),
array(array(1, 2, 2, 3, 2, 2), 	array('Ritsu: Japan, Raga Suddha Todi)')),
array(array(2, 2, 1, 2, 2, 3), 	array('Arezzo Major Diatonic Hexachord, Raga Kambhoji, Devarangini, Sama (Syama), Scottish Hexatonic')),
array(array(2, 1, 2, 2, 3, 2), 	array('Minor Hexatonic, Raga Manirangu, Nayaki, Palasi, Pushpalithika (Puspalatika), Suha Sughrai, Yo: Japan, Eskimo Hexatonic 1 (Alaska: King Island)'),
array(array(2, 2, 2, 2, 3, 1), 	array('Eskimo Hexatonic 2 (Alaska: Point Hope))')),
array(array(2, 1, 4, 2, 2, 1), 	array('Hawaiian')),
array(array(2, 1, 2, 1, 3, 3), 	array('Pyramid Hexatonic')),
array(array(1, 2, 1, 2, 1, 5), 	array('Istrian: Croatia')),
array(array(1, 2, 2, 1, 3, 3), 	array('Double-Phrygian Hexatonic')),
array(array(2, 1, 3, 1, 4, 1), 	array('Raga Amarasenapriya')),
array(array(2, 1, 2, 4, 1, 2), 	array('Raga Bagesri, Sriranjani, Kapijingla, Jayamanohari')),
array(array(1, 3, 3, 1, 3, 1), 	array('Raga Bauli')),
array(array(3, 1, 1, 2, 3, 2), 	array('Raga Bhanumanjari, Jog')),
array(array(1, 2, 3, 2, 2, 2), 	array('Raga Bhavani')),
array(array(2, 3, 2, 1, 3, 1), 	array('Raga Bhinna Pancama')),
array(array(2, 2, 2, 1, 4, 1), 	array('Raga Caturangini, Ratnakanthi')),
array(array(1, 1, 4, 1, 2, 3), 	array('Raga Chandrajyoti')),
array(array(1, 3, 2, 1, 1, 4), 	array('Raga Dhavalangam')),
array(array(2, 2, 1, 1, 1, 5), 	array('Raga Dipak')),
array(array(1, 2, 2, 2, 3, 2), 	array('Raga Gandharavam, Sabai silt: Ethiopia')),
array(array(1, 3, 1, 2, 4, 1), 	array('Raga Gaula')),
array(array(2, 1, 2, 3, 3, 1), 	array('Raga Ghantana, Kaushiranjani (Kaishikiranjani)')),
array(array(3, 2, 2, 1, 2, 2), 	array('Raga Gopikavasantam, Desya Todi, Jayantasri, Phrygian Hexatonic')),
array(array(1, 2, 3, 2, 3, 1), 	array('Raga Gurjari Todi')),
array(array(1, 3, 2, 3, 2, 1), 	array('Raga Hamsanandi, Marva, Pancama, Puriya, Sohni')),
array(array(2, 2, 1, 4, 2, 1), 	array('Raga Hamsa Vinodini')),
array(array(4, 1, 2, 2, 2, 1), 	array('Raga Hari Nata, Genus secundum')),
array(array(1, 3, 2, 2, 1, 3), 	array('Raga Hejjajji')),
array(array(2, 4, 1, 1, 2, 2), 	array('Raga Jaganmohanam')),
array(array(1, 4, 2, 2, 2, 1), 	array('Raga Jivantika')),
array(array(3, 3, 1, 3, 1, 1), 	array('Raga Jivantini, Gaurikriya')),
array(array(4, 2, 1, 1, 2, 2), 	array('Raga Jyoti')),
array(array(1, 3, 3, 1, 1, 3), 	array('Raga Kalagada (Kalgada)')),
array(array(1, 4, 2, 1, 1, 3), 	array('Raga Kalakanthi')),
array(array(1, 3, 1, 2, 2, 3), 	array('Raga Kalavati, Ragamalini')),
array(array(4, 1, 2, 1, 2, 2), 	array('Raga Kamalamanohari')),
array(array(1, 2, 4, 1, 2, 2), 	array('Raga Kashyapi')),
array(array(4, 1, 2, 2, 1, 2), 	array('Raga Khamas, Desya Khamas, Bahudari')),
array(array(2, 2, 3, 2, 2, 1), 	array('Raga Kumud, Sankara (Shankara), Prabhati, Lydian Hexatonic')),
array(array(1, 3, 1, 3, 3, 1), 	array('Raga Lalita, Sohini, Hamsanandi, Lalit Bhairav')),
array(array(2, 2, 3, 1, 3, 1), 	array('Raga Latika')),
array(array(3, 3, 1, 2, 1, 2), 	array('Raga Madhukauns (hexatonic)')),
array(array(2, 4, 1, 3, 1, 1), 	array('Raga Malarani, Hamsanada')),
array(array(1, 3, 3, 2, 1, 2), 	array('Raga Malayamarutam')),
array(array(2, 1, 4, 2, 1, 2), 	array('Raga Manavi')),
array(array(1, 3, 2, 1, 4, 1), 	array('Raga Mandari, Gamakakriya, Hamsanarayani')),
array(array(3, 2, 2, 2, 1, 2), 	array('Raga Manohari, Malavasri')),
array(array(2, 2, 2, 3, 2, 1), 	array('Raga Mruganandana')),
array(array(2, 3, 2, 2, 2, 1), 	array('Raga Nagagandhari')),
array(array(2, 2, 1, 2, 4, 1), 	array('Raga Nalinakanti, Kedaram, Vilasini')),
array(array(2, 3, 2, 1, 2, 2), 	array('Raga Navamanohari')),
array(array(2, 1, 3, 2, 1, 3), 	array('Raga Neelangi')),
array(array(2, 4, 1, 2, 2, 1), 	array('Raga Nishadi')),
array(array(1, 4, 2, 1, 3, 1), 	array('Raga Padi')),
array(array(4, 1, 2, 1, 3, 1), 	array('Raga Paraju (Paraz, Pharas), Ramamanohari, Sindhu Ramakriya, Kamalamanohari')),
array(array(1, 4, 2, 1, 2, 2), 	array('Raga Phenadyuti, Insen, Honchoshi, Niagari: Japan')),
array(array(1, 2, 2, 1, 4, 2), 	array('Honchoshi plagal form: Japan')),
array(array(1, 3, 1, 2, 1, 4), 	array('Raga Purna Pancama, Malahari, Geyahejjajji, Kannadabangala')),
array(array(2, 2, 1, 4, 1, 2), 	array('Raga Rageshri (Rageshwari), Nattaikurinji (Natakuranji)')),
array(array(2, 1, 3, 3, 2, 1), 	array('Raga Ranjani, Rangini')),
array(array(3, 1, 2, 1, 4, 1), 	array('Raga Rasamanjari')),
array(array(1, 4, 2, 2, 1, 2), 	array('Raga Rasavali')),
array(array(1, 3, 1, 4, 1, 2), 	array('Raga Rudra Pancama')),
array(array(1, 2, 4, 2, 1, 2), 	array('Raga Salagavarali')),
array(array(2, 3, 2, 3, 1, 1), 	array('Raga Brindabani Sarang, Megh (Megh Malhar)')),
array(array(2, 2, 1, 3, 3, 1), 	array('Raga Sarasanana')),
array(array(2, 4, 1, 2, 1, 2), 	array('Raga Sarasvati')),
array(array(4, 1, 2, 1, 1, 3), 	array('Raga Saravati (Sharavati)')),
array(array(2, 1, 3, 1, 3, 2), 	array('Raga Simharava (Sinharavam), Gopikatilaka')),
array(array(2, 1, 2, 2, 4, 1), 	array('Raga Sindhura Kafi')),
array(array(2, 2, 1, 2, 3, 2), 	array('Raga Siva Kambhoji, Vivardhini, Andhali')),
array(array(2, 1, 2, 2, 2, 3), 	array('Raga Suddha Bangala, Gauri Velavali')),
array(array(1, 1, 3, 3, 1, 3), 	array('Raga Suddha Mukhari')),
array(array(1, 2, 2, 2, 1, 4), 	array('Raga Suddha Simantini')),
array(array(2, 1, 3, 1, 1, 4), 	array('Raga Syamalam')),
array(array(3, 2, 2, 1, 3, 1), 	array('Raga Takka')),
array(array(4, 1, 2, 3, 1, 1), 	array('Raga Tilang, Savitri, Brindabani Tilang')),
array(array(2, 1, 4, 1, 2, 2), 	array('Raga Trimurti')),
array(array(1, 3, 1, 4, 2, 1), 	array('Raga Vasanta, Chayavati')),
array(array(1, 3, 1, 3, 2, 2), 	array('Raga Vasantabhairavi')),
array(array(2, 1, 3, 1, 2, 3), 	array('Raga Vijayanagari')),
array(array(1, 1, 4, 1, 4, 1), 	array('Raga Vijayasri')),
array(array(4, 2, 1, 3, 1, 1), 	array('Raga Vijayavasanta')),
array(array(1, 2, 2, 3, 3, 1), 	array('Raga Viyogavarali')),
array(array(4, 2, 1, 2, 1, 2), 	array('Raga Vutari')),
array(array(2, 2, 2, 1, 2, 3), 	array('Raga Yamuna Kalyani, Kalyani Keseri, Airavati, Ancient Chinese')),
array(array(1, 1, 4, 1, 1, 4), 	array('Messiaen mode 5', 'Two-semitone Tritone scale')),
array(array(4, 1, 1, 4, 1, 1), 	array('Messiaen mode 5 inverse')),
array(array(1, 3, 1, 3, 1, 3), 	array('Messiaen truncated mode 3', 'Prometheus (Liszt)')),
array(array(3, 1, 3, 1, 3, 1), 	array('Messiaen truncated mode 3 inverse', 'Major Augmented', 'Genus tertium', 'Raga Devamani')),
array(array(1, 2, 3, 1, 2, 3), 	array('Messiaen truncated mode 2')),
array(array(1, 3, 2, 1, 3, 2), 	array('Messiaen truncated mode 2', 'Raga Indupriya', 'Tritone scale')),
array(array(3, 1, 2, 2, 1, 3), 	array('Equal temperaments 3 and 4 mixed')),
array(array(1, 2, 1, 2, 4, 2), 	array('Superlocrian Hexamirror')),
array(array(2, 1, 3, 2, 3, 1), 	array('Takemitsu Tree Line mode 1')),
array(array(2, 1, 3, 2, 2, 2), 	array('Takemitsu Tree Line mode 2')),

array(array(1, 2, 2, 1, 2, 2, 2), 	array('Greek Mixolydian', 'Greek Hyperdorian', 'Medieval Hypophrygian', 'Medieval Locrian', 'Greek Medieval Hyperaeolian', 'Rut biscale descending', 'Pien chih: China', 'Makam Lami', 'Yishtabach: Jewish')),
array(array(2, 2, 1, 2, 2, 2, 1), 	array('Greek Lydian', 'Medieval Ionian', 'Medieval Hypolydian', 'Major', 'Bilaval That', 'Mela Shankarabharanam', 'Raga Atana', 'Ghana Heptatonic', 'Peruvian Major', 'Matzore', 'Rast ascending: Greece', '4th plagal Byzantine', 'Ararai: Ethiopia', 'Makam Cargah', 'Ajam Ashiran', 'Dastgah-e Mahur', 'Dastgah-e Rast Panjgah', 'Xin: China, DS2')),
array(array(2, 1, 2, 2, 2, 1, 2), 	array('Greek Phrygian', 'Medieval Dorian', 'Medieval Hypomixolydian', 'Kafi That', 'Mela Kharaharapriya', 'Raga Bageshri', 'Bhimpalasi', 'Nayaki Kanada', 'Sriraga', 'Ritigaula', 'Huseni', 'Kanara', 'Mischung 5', 'Gregorian nr.8', 'Eskimo Heptatonic', 'Yu: China', 'Hyojo', 'Oshikicho', 'Banshikicho: Japan', 'Nam: Vietnam')),
array(array(1, 2, 2, 2, 1, 2, 2), 	array('Greek Dorian', 'Medieval Phrygian', 'Greek Medieval Hypoaeolian', 'Bhairavi That', 'Mela Hanumatodi', 'Raga Asavari (Asaveri)', 'Bilashkhani Todi', 'Ghanta', 'Makam Kurd', 'Gregorian nr.3', 'In', 'Zokuso: Japan', 'Ousak: Greece', 'Major inverse')),
array(array(2, 2, 2, 1, 2, 2, 1), 	array('Greek Hypolydian', 'Medieval Lydian', 'Greek Medieval Hypolocrian', 'Rut biscale ascending', 'Kalyan That (Yaman)', 'Mela Mecakalyani', 'Raga Shuddh Kalyan', 'Ping', 'Kung', 'Gu: China')),
array(array(2, 2, 1, 2, 2, 1, 2), 	array('Greek Hypophrygian', 'Greek Ionian (Iastian)', 'Medieval Mixolydian', 'Greek Medieval Hypoionian', 'Hypermixolydian', 'Khamaj That', 'Mela Harikambhoji', 'Raga Harini', 'Janjhuti', 'Khambhavati', 'Surati', 'Balahamsa', 'Devamanohari', 'Mischung 3', 'Gregorian nr.7', 'Enharmonic Byzantine Liturgical', 'Rast descending: Greece', 'Ching', 'Shang: China')),
array(array(2, 1, 2, 2, 1, 2, 2), 	array('Greek Medieval Hypodorian', 'Greek Medieval Aeolian', 'Greek Hyperphrygian', 'Natural Minor', 'Melodic Minor descending', 'Asavari That', 'Mela Natabhairavi', 'Raga Jaunpuri', 'Adana', 'Darbari', 'Dhanyasi', 'Jingla', 'Gregorian nr.2', 'Makam Buselik', 'Nihavend', 'Peruvian Minor', 'Se', 'Chiao: China', 'Geez', 'Ezel: Ethiopia', 'Kiourdi descending: Greece', 'Cushak: Armenia'),
array(array(1, 1, 3, 1, 1, 3, 2), 	array('Chromatic Mixolydian')),
array(array(1, 3, 1, 1, 3, 2, 1), 	array('Chromatic Lydian', 'Raga Lalit, Bhankar')),
array(array(3, 1, 1, 3, 2, 1, 1), 	array('Chromatic Phrygian')),
array(array(1, 1, 3, 2, 1, 1, 3), 	array('Chromatic Dorian', 'Mela Kanakangi', 'Raga Kanakambari')),
array(array(1, 3, 2, 1, 1, 3, 1), 	array('Chromatic Hypolydian', 'Purvi That', 'Mela Kamavardhani', 'Raga Shri', 'Pantuvarali', 'Basant', 'Kasiramakriya', 'Suddharamakriya', 'Puriya Dhanashri', 'Dhipaka', 'Pireotikos: Greece'),
array(array(3, 2, 1, 1, 3, 1, 1), 	array('Chromatic Hypophrygian', 'Blues scale III')),
array(array(2, 1, 1, 3, 1, 1, 3), 	array('Chromatic Hypodorian', 'Relative Blues scale', 'Raga Dvigandharabushini')),
array(array(2, 3, 1, 1, 3, 1, 1), 	array('Chromatic Mixolydian inverse')),
array(array(1, 1, 2, 3, 1, 1, 3), 	array('Chromatic Phrygian inverse')),
array(array(1, 1, 3, 1, 1, 2, 3), 	array('Chromatic Hypophrygian inverse')),
array(array(3, 1, 1, 3, 1, 1, 2), 	array('Chromatic Hypodorian inverse')),
array(array(2, 1, 2, 2, 2, 2, 1), 	array('Melodic Minor ascending', 'Jazz Minor', 'Minor-Major', 'Mela Gaurimanohari', 'Raga Patdip', 'Velavali', 'Deshi(2)', 'Mischung 1', 'Hawaiian'),
array(array(2, 1, 2, 2, 1, 3, 1), 	array('Harmonic Minor', 'Mischung 4', 'Pilu That', 'Mela Kiravani', 'Raga Kiranavali', 'Kirvani', 'Kalyana Vasantha', 'Deshi(3)', 'Maqam Bayat-e-Esfahan', 'Sultani Yakah', 'Zhalibny Minor', 'Armoniko minore: Greece'),
array(array(1, 3, 1, 2, 2, 1, 2), 	array('Harmonic Minor inverse', 'Mela Cakravaka', 'Raga Ahir Bhairav', 'Bindumalini', 'Vegavahini', 'Makam Hicaz', 'Zanjaran')),
array(array(2, 2, 1, 2, 1, 3, 1), 	array('Harmonic Major', 'Mela Sarasangi', 'Raga Haripriya', 'Simhavahini', 'Mischung 2', 'Ethiopian', 'Tabahaniotikos: Greece')),
array(array(1, 2, 1, 3, 1, 2, 2), 	array('Makam Huzzam', 'Maqam Saba Zamzam', 'Phrygian flat 4')),
array(array(2, 2, 1, 3, 1, 2, 1), 	array('Ionian Augmented', 'Ionian sharp 5')),
array(array(2, 2, 2, 2, 1, 2, 1), 	array('Lydian Augmented', 'Lydian sharp 5')),
array(array(1, 2, 2, 1, 3, 1, 2), 	array('Locrian natural 6', 'Maqam Tarznauyn')),
array(array(2, 2, 1, 1, 2, 2, 2), 	array('Major Locrian')),
array(array(2, 1, 2, 1, 2, 2, 2), 	array('Minor Locrian', 'Half Diminished', 'Locrian sharp 2', 'Minor flat 5')),
array(array(1, 2, 1, 2, 2, 2, 2), 	array('Superlocrian', 'Altered Dominant', 'Diminished Whole-tone', 'Locrian flat 4', 'Pomeroy', 'Ravel')),
array(array(2, 1, 2, 1, 2, 3, 1), 	array('Locrian nr.2')),
array(array(1, 2, 1, 2, 2, 1, 3), 	array('Ultralocrian', 'Superlocrian Diminished', 'Mixolydian sharp 1')),
array(array(1, 2, 2, 1, 2, 1, 3), 	array('Locrian double-flat 7')),
array(array(2, 3, 1, 2, 1, 2, 1), 	array('Nohkan Flute scale: Japan')),
array(array(2, 1, 1, 3, 1, 2, 2), 	array('Sabach (Sambah) ascending: Greece')),
array(array(2, 1, 2, 1, 3, 1, 2), 	array('Dorian flat 5', 'Blues Heptatonic', 'Makam Karcigar', 'Maqam Nahawand Murassah', 'Kiourdi ascending', 'Kartzihiar: Greece')),
array(array(3, 2, 1, 1, 2, 1, 2), 	array('Blues Heptatonic II')),
array(array(2, 1, 2, 1, 3, 2, 1), 	array('Jeths\' mode')),
array(array(1, 1, 3, 2, 1, 2, 2), 	array('Mela Ratnangi', 'Raga Phenadyuti')),
array(array(1, 1, 3, 2, 1, 3, 1), 	array('Mela Ganamurti', 'Raga Ganasamavarali')),
array(array(1, 1, 3, 2, 2, 1, 2), 	array('Mela Vanaspati', 'Raga Bhanumati')),
array(array(1, 1, 3, 2, 2, 2, 1), 	array('Mela Manavati', 'Raga Manoranjani')),
array(array(1, 1, 3, 2, 3, 1, 1), 	array('Mela Tanarupi', 'Raga Tanukirti')),
array(array(1, 2, 2, 2, 1, 1, 3), 	array('Mela Senavati', 'Raga Senagrani, Malini')),
array(array(1, 2, 2, 2, 1, 3, 1), 	array('Neapolitan Minor', 'Mela Dhenuka', 'Raga Bhinnasadjam', 'Dhunibinnashadjam', 'Kirvanti', 'Takka', 'Maqam Shahnaz Kurdi', 'Hungarian Gipsy'),
array(array(1, 2, 2, 2, 2, 2, 1), 	array('Neapolitan Major', 'Lydian Major', 'Mela Kokilapriya', 'Raga Kokilaravam')),
array(array(1, 2, 2, 2, 2, 1, 2), 	array('Mela Natakapriya', 'Jazz Minor inverse', 'Phrygian-Mixolydian', 'Dorian flat 2', 'Raga Natabharanam', 'Ahiri Todi')),
array(array(1, 2, 2, 2, 3, 1, 1), 	array('Mela Rupavati')),
array(array(1, 3, 1, 1, 2, 3, 1), 	array('Raga Lalita', 'Persian', 'Chromatic Hypolydian inverse', 'Raga Suddha Pancama')),
array(array(1, 3, 1, 2, 1, 1, 3), 	array('Mela Gayakapriya', 'Raga Kalakanti', 'Gipsy Hexatonic')),
array(array(1, 3, 1, 2, 1, 2, 2), 	array('Phrygian Dominant, Phrygian Major, Mela Vakulabharanam, Raga Jogiya, Ahiri, Vativasantabhairavi, Zilof, Ahava Rabba, Freygish: Jewish, Maqam Hijaz-Nahawand, Humayun, Spanish Gipsy, Dorico Flamenco: Spain, Hitzaz: Greece, Harmonic Major inverse'),
array(array(1, 3, 1, 2, 1, 3, 1), 	array('Major Gipsy', 'Double Harmonic Major', 'Bhairav That', 'Mela Mayamalavagaula', 'Raga Paraj', 'Kalingada', 'Gaulipantu', 'Lalitapancamam', 'Chromatic 2nd Byzantine Liturgical', 'Hitzazkiar: Greece', 'Maqam Zengule', 'Hijaz Kar', 'Suzidil'),
array(array(1, 3, 1, 2, 2, 2, 1), 	array('Mela Suryakanta', 'Bhairubahar That', 'Raga Supradhipam', 'Sowrashtram', 'Jaganmohini', 'Major-Melodic Phrygian', 'Hungarian Gipsy inverse'),
array(array(1, 3, 1, 2, 3, 1, 1), 	array('Mela Hatakambari', 'Raga Jeyasuddhamalavi')),
array(array(2, 1, 2, 1, 1, 3, 2), 	array('Modified Blues')),
array(array(2, 1, 2, 2, 1, 1, 3), 	array('Mela Jhankaradhvani', 'Raga Jhankara Bhramavi')),
array(array(2, 1, 2, 2, 3, 1, 1), 	array('Mela Varunapriya', 'Viravasantham')),
array(array(2, 2, 1, 2, 1, 1, 3), 	array('Mela Mararanjani', 'Raga Keseri', 'Major Bebop Heptatonic')),
array(array(2, 2, 1, 2, 1, 2, 2), 	array('Major-Minor', 'Melodic Major', 'Mischung 6', 'Mixolydian flat 6', 'Mela Carukesi', 'Raga Charukeshi', 'Tarangini')),
array(array(2, 2, 1, 2, 3, 1, 1), 	array('Mela Naganandini', 'Raga Nagabharanam', 'Samanta')),
array(array(3, 1, 1, 2, 1, 1, 3), 	array('Mela Yagapriya', 'Raga Kalahamsa')),
array(array(3, 1, 1, 2, 1, 2, 2), 	array('Mela Ragavardhani', 'Raga Cudamani')),
array(array(3, 1, 1, 2, 1, 3, 1), 	array('Mela Gangeyabhusani', 'Raga Gangatarangini', 'Sengiach (Sengah): Greece', 'Gipsy Hexatonic inverse')),
array(array(3, 1, 1, 2, 2, 1, 2), 	array('Mela Vagadhisvari', 'Raga Bhogachayanata', 'Nandkauns', 'Ganavaridhi', 'Chayanata', 'Bluesy Rock \'n Roll')),
array(array(3, 1, 1, 2, 2, 2, 1), 	array('Mela Sulini', 'Raga Sailadesakshi', 'Raga Trishuli', 'Houzam: Greece')),
array(array(3, 1, 1, 2, 3, 1, 1), 	array('Mela Calanata', 'Raga None', 'Chromatic Dorian inverse')),
array(array(1, 1, 4, 1, 1, 1, 3), 	array('Mela Salaga')),
array(array(1, 1, 4, 1, 1, 2, 2), 	array('Mela Jalarnava')),
array(array(1, 1, 4, 1, 1, 3, 1), 	array('Mela Jhalavarali', 'Raga Varali', 'Jinavali')),
array(array(1, 1, 4, 1, 2, 1, 2), 	array('Mela Navanitam', 'Raga Nabhomani')),
array(array(1, 1, 4, 1, 2, 2, 1), 	array('Mela Pavani', 'Raga Kumbhini')),
array(array(1, 1, 4, 1, 3, 1, 1), 	array('Mela Raghupriya', 'Raga Ravikriya', 'Ghandarva')),
array(array(1, 2, 3, 1, 1, 1, 3), 	array('Mela Gavambodhi', 'Raga Girvani')),
array(array(1, 2, 3, 1, 1, 2, 2), 	array('Mela Bhavapriya', 'Raga Bhavani', 'Kalamurti', 'Neveseri ascending: Greece')),
array(array(1, 2, 3, 1, 1, 3, 1), 	array('Todi That', 'Mela Shubhapantuvarali', 'Raga Multani', 'Gamakasamantam', 'Harsh Minor', 'Chromatic Lydian inverse', 'Maqam Athar Kurd')),
array(array(1, 2, 3, 1, 2, 1, 2), 	array('Mela Sadvidhamargini', 'Raga Sthavarajam', 'Tivravahini')),
array(array(1, 2, 3, 1, 2, 2, 1), 	array('Mela Suvarnangi', 'Raga Sauviram')),
array(array(1, 2, 3, 1, 3, 1, 1), 	array('Mela Divyamani')),
array(array(1, 3, 2, 1, 1, 1, 3), 	array('Mela Dhavalambari', 'Foulds\' Mantra of Will scale')),
array(array(1, 3, 2, 1, 1, 2, 2), 	array('Mela Namanarayani', 'Raga Narmada', 'Pratapa', 'Harsh Major-Minor')),
array(array(1, 3, 2, 1, 2, 1, 2), 	array('Mela Ramapriya', 'Raga Ramamanohari', 'Romanian Major', 'Petrushka chord')),
array(array(1, 3, 2, 1, 2, 2, 1), 	array('Marva That', 'Mela Gamanasrama', 'Raga Partiravam', 'Puriya', 'Puriya Kalyan', 'Purvikalyani', 'Sohani', 'Bairari', 'Harsh-intense Major', 'Peiraiotikos: Greece')),
array(array(1, 3, 2, 1, 3, 1, 1), 	array('Mela Visvambhari', 'Raga Vamsavathi')),
array(array(1, 3, 2, 2, 2, 1, 1), 	array('Verdi\'s Scala enigmatica ascending')),
array(array(1, 3, 1, 3, 2, 1, 1), 	array('Verdi\'s Scala enigmatica descending')),
array(array(2, 1, 2, 1, 2, 1, 3), 	array('Moravian Pistalkova', 'Hungarian Major inverse')),
array(array(2, 1, 3, 1, 1, 1, 3), 	array('Mela Syamalangi', 'Raga Shyamalam')),
array(array(2, 1, 3, 1, 1, 2, 2), 	array('Minor Gipsy', 'Ukrainian Dorian', 'Mela Sanmukhapriya', 'Raga Camara', 'Chinthamani')),
array(array(2, 1, 3, 1, 1, 3, 1), 	array('Double Harmonic Minor', 'Hungarian Minor', 'Egyptian Heptatonic', 'Mela Simhendramadhyama', 'Raga Madhava Manohari', 'Maqam Nawa Athar', 'Hisar', 'Flamenco Mode', 'Niavent: Greece')),
array(array(2, 1, 3, 1, 2, 1, 2), 	array('Mela Hemavati', 'Raga Desisimharavam', 'Maqam Nakriz', 'Tunisian', 'Dorian sharp 4', 'Misheberekh: Jewish', 'Souzinak (Peiraiotikos) Minor', 'Nigriz', 'Pimenikos: Greece', 'Ukrainian Minor', 'Kaffa', 'Gnossiennes')),
array(array(2, 1, 3, 1, 2, 2, 1), 	array('Lydian Diminished', 'Mela Dharmavati', 'Raga Arunajualita', 'Dumyaraga', 'Madhuvanti', 'Ambika')),
array(array(2, 1, 3, 1, 3, 1, 1), 	array('Mela Nitimati', 'Raga Nisada', 'Kaikavasi')),
array(array(2, 2, 1, 1, 3, 1, 2), 	array('Minor Gipsy inverse')),
array(array(2, 2, 2, 1, 1, 1, 3), 	array('Mela Kantamani', 'Raga Kuntala', 'Srutiranjani')),
array(array(2, 2, 2, 1, 1, 2, 2), 	array('Lydian Minor', 'Mela Risabhapriya', 'Raga Ratipriya')),
array(array(2, 2, 2, 1, 1, 3, 1), 	array('Harmonic Lydian', 'Mela Latangi', 'Raga Gitapriya', 'Hamsalata')),
array(array(2, 2, 2, 1, 2, 1, 2), 	array('Lydian Dominant', 'Mela Vacaspati', 'Raga Bhusavati', 'Bhusavali', 'Overtone', 'Lydian-Mixolydian', 'Bartok')),
array(array(2, 2, 2, 1, 3, 1, 1), 	array('Mela Citrambari', 'Raga Chaturangini')),
array(array(2, 2, 1, 4, 1, 1, 1), 	array('Raga Rageshri')),
array(array(2, 3, 2, 2, 1, 1, 1), 	array('Raga Sorati', 'Sur Malhar')),
array(array(3, 1, 2, 1, 1, 1, 3), 	array('Mela Sucaritra', 'Raga Santanamanjari')),
array(array(3, 1, 2, 1, 1, 2, 2), 	array('Mela Jyotisvarupini', 'Raga Jotismatti')),
array(array(3, 1, 2, 1, 1, 3, 1), 	array('Mela Dhatuvardhani', 'Raga Dhauta Pancama', 'Devarashtra')),
array(array(3, 1, 2, 1, 2, 1, 2), 	array('Hungarian Major', 'Mela Nasikabhusani', 'Raga Nasamani')),
array(array(3, 1, 2, 1, 2, 2, 1), 	array('Aeolian Harmonic', 'Lydian sharp 2', 'Mela Kosalam', 'Raga Kusumakaram')),
array(array(3, 1, 2, 1, 3, 1, 1), 	array('Mela Rasikapriya', 'Raga Rasamanjari', 'Hamsagiri')),
array(array(3, 1, 2, 2, 1, 2, 1), 	array('Aeolian flat 1')),
array(array(4, 1, 2, 2, 1, 1, 1), 	array('Raga Madhuri')),
array(array(1, 3, 1, 1, 3, 1, 2), 	array('Oriental', 'Raga Ahira-Lalita', 'Hungarian Minor inverse', 'Tsinganikos: Greece')),
array(array(2, 2, 2, 2, 2, 1, 1), 	array('Leading Whole-tone')),
array(array(1, 1, 2, 2, 2, 2, 2), 	array('Leading Whole-tone inverse')),
array(array(2, 1, 1, 1, 1, 3, 3), 	array('Debussy\'s Heptatonic')),
array(array(1, 3, 1, 1, 1, 2, 2, 1), 	array('Raga Bhatiyar')),
array(array(2, 1, 3, 1, 1, 1, 1, 2), 	array('Raga Cintamani')),
array(array(2, 1, 2, 2, 2, 1, 1, 1), 	array('Raga Mian Ki Malhar', 'Bahar', 'Sindhura')),
array(array(2, 1, 2, 2, 1, 1, 1, 2), 	array('Raga Mukhari', 'Anandabhairavi', 'Deshi', 'Manji', 'Gregorian nr.1', 'Dorian/Aeolian mixed')),
array(array(1, 3, 1, 1, 1, 1, 3, 1), 	array('Raga Ramkali (Ramakri)')),
array(array(1, 3, 1, 2, 1, 1, 2, 1), 	array('Raga Saurashtra')),
array(array(2, 1, 1, 3, 1, 2, 1, 1), 	array('Sabach (Sambah): Greece')),
array(array(2, 1, 1, 1, 2, 2, 1, 2), 	array('Minor Bebop', 'Dorian Bebop', 'Raga Zilla', 'Mixolydian/Dorian mixed')),
array(array(2, 2, 1, 2, 2, 1, 1, 1), 	array('Genus diatonicum', 'Dominant Bebop', 'Raga Khamaj', 'Desh Malhar', 'Alhaiya Bilaval', 'Devagandhari', 'Bihagara', 'Maqam Shawq Awir', 'Gregorian nr.6', 'Major/Mixolydian mixed', 'Chinese Eight-Tone', 'Rast: Greece'),
array(array(2, 2, 1, 2, 1, 1, 2, 1), 	array('Major Bebop', 'Altered Mixolydian')),
array(array(2, 1, 2, 1, 1, 2, 1, 2), 	array('Blues scale II')),
array(array(2, 1, 2, 1, 1, 1, 3, 1), 	array('Algerian', 'Sabiren')),
array(array(1, 2, 1, 1, 2, 1, 2, 2), 	array('Spanish Phrygian')),
array(array(1, 2, 1, 1, 1, 2, 2, 2), 	array('Espla\'s scale', 'Eight-tone Spanish')),
array(array(1, 2, 2, 1, 1, 1, 3, 1), 	array('Half-diminished Bebop')),
array(array(1, 2, 2, 2, 1, 1, 2, 1), 	array('Neapolitan Major and Minor mixed')),
array(array(1, 2, 3, 1, 1, 2, 1, 1), 	array('Neveseri: Greece')),
array(array(2, 1, 2, 1, 2, 1, 2, 1), 	array('Diminished', 'Modus conjunctus', 'Messiaen mode 2 inverse', 'Whole-Half step scale')),
array(array(2, 2, 1, 1, 1, 2, 2, 1), 	array('Ishikotsucho: Japan', 'Raga Yaman Kalyan', 'Chayanat', 'Bihag', 'Hamir Kalyani', 'Kedar', 'Gaud Sarang', 'Genus diatonicum veterum correctum', 'Gregorian nr.5', 'Kubilai\'s Mongol scale', 'Major/Lydian mixed'))),
array(array(1, 3, 1, 1, 2, 2, 1, 1), 	array('Verdi\'s Scala enigmatica')),
array(array(2, 1, 2, 2, 1, 1, 2, 1), 	array('Zirafkend: Arabic', 'Melodic Minor Bebop')),
array(array(1, 1, 1, 2, 2, 2, 1, 2), 	array('Adonai Malakh: Jewish')),
array(array(1, 2, 1, 2, 2, 1, 2, 1), 	array('Magen Abot: Jewish')),
array(array(2, 1, 2, 2, 1, 2, 1, 1), 	array('Maqam Nahawand', 'Farahfaza', 'Raga Suha (Suha Kanada)', 'Gregorian nr.4', 'Utility Minor')),
array(array(1, 1, 1, 2, 2, 1, 3, 1), 	array('Harmonic and Neapolitan Minor mixed')),
array(array(1, 3, 1, 2, 1, 2, 1, 1), 	array('Maqam Hijaz (Hedjaz)')),
array(array(1, 2, 1, 1, 1, 3, 1, 2), 	array('Maqam Shadd\'araban')),
array(array(1, 2, 1, 2, 1, 2, 1, 2), 	array('Octatonic', 'Messiaen mode 2', 'Dominant Diminished', 'Diminished Blues', 'Half-Whole step scale')),
array(array(1, 1, 1, 3, 1, 1, 1, 3), 	array('Messiaen mode 4', 'Tcherepnin Octatonic mode 3')),
array(array(3, 1, 1, 1, 3, 1, 1, 1), 	array('Messiaen mode 4 inverse', 'Tcherepnin Octatonic mode 4')),
array(array(1, 1, 2, 2, 1, 1, 2, 2), 	array('Messiaen mode 6')),
array(array(2, 2, 1, 1, 2, 2, 1, 1), 	array('Messiaen mode 6 inverse')),
array(array(1, 3, 1, 1, 1, 3, 1, 1), 	array('Tcherepnin Octatonic mode 1')),
array(array(1, 1, 3, 1, 1, 1, 3, 1), 	array('Tcherepnin Octatonic mode 2')),
array(array(1, 1, 1, 2, 2, 1, 2, 2), 	array('Phrygian/Aeolian mixed')),
array(array(1, 2, 2, 1, 1, 1, 2, 2), 	array('Phrygian/Locrian mixed')),
array(array(1, 2, 2, 2, 1, 2, 1, 1), 	array('Hamel')),
array(array(1, 2, 2, 1, 1, 2, 2, 1), 	array('Van der Horst Octatonic')),
array(array(1, 2, 2, 1, 2, 2, 1, 1), 	array('Prokofiev')),
array(array(1, 2, 1, 2, 1, 2, 2, 1), 	array('Shostakovich')),
array(array(1, 2, 1, 1, 2, 2, 1, 2), 	array('JG Octatonic')),
array(array(2, 1, 1, 2, 2, 1, 1, 2), 	array('Equal temperaments 4 and 6 mixed')),
array(array(1, 1, 2, 1, 1, 2, 1, 1, 2), 	array('Messiaen mode 3', 'Tcherepnin Nonatonic mode 3')),
array(array(2, 1, 1, 2, 1, 1, 2, 1, 1), 	array('Messiaen mode 3 inverse', 'Tcherepnin Nonatonic mode 2')),
array(array(2, 1, 2, 2, 1, 1, 1, 1, 1), 	array('Raga Pilu', 'Full Minor')),
array(array(2, 1, 1, 1, 2, 2, 1, 1, 1), 	array('Raga Malgunji', 'Ramdasi Malhar', 'Major/Dorian mixed', 'Blues Enneatonic')),
array(array(2, 2, 1, 2, 1, 1, 1, 1, 1), 	array('Raga Pahadi')),
array(array(2, 1, 1, 1, 1, 1, 2, 1, 2), 	array('Blues Enneatonic II')),
array(array(2, 1, 2, 1, 1, 1, 1, 1, 2), 	array('Kiourdi: Greece')),
array(array(2, 2, 1, 1, 1, 2, 1, 1, 1), 	array('Taishikicho', 'Ryo: Japan', 'Raga Chayanat', 'Lydian/Mixolydian mixed')),
array(array(1, 1, 2, 1, 2, 2, 1, 1, 1), 	array('Chromatic Bebop')),
array(array(1, 1, 1, 2, 1, 1, 1, 2, 2), 	array('Locrian/Aeolian mixed')),
array(array(1, 2, 1, 1, 2, 1, 1, 2, 1), 	array('Genus chromaticum', 'Tcherepnin Nonatonic mode 1', 'Augmented-9')),
array(array(1, 2, 1, 1, 2, 1, 2, 1, 1), 	array('Moorish Phrygian', 'Phrygian/Double Harmonic Major mixed')),
array(array(1, 1, 2, 1, 1, 1, 2, 1, 2), 	array('Youlan scale: China')),
array(array(1, 1, 1, 2, 2, 1, 1, 1, 2), 	array('Chromatic and Diatonic Dorian mixed')),
array(array(1, 1, 2, 1, 2, 1, 1, 2, 1), 	array('Chromatic and Permuted Diatonic Dorian mixed')),
array(array(2, 1, 1, 1, 2, 1, 1, 1, 2), 	array('Houseini: Greece, Modes of Major Pentatonic mixed')),
array(array(1, 1, 1, 1, 2, 1, 1, 1, 1, 2), 		array('Messiaen mode 7')),
array(array(2, 1, 1, 1, 1, 2, 1, 1, 1, 1), 		array('Messiaen mode 7 inverse')),
array(array(2, 1, 1, 1, 2, 1, 1, 1, 1, 1), 		array('Major/Minor mixed')),
array(array(2, 1, 1, 1, 1, 1, 2, 1, 1, 1), 		array('Minor Pentatonic with leading tones')),
array(array(2, 1, 1, 1, 1, 1, 1, 1, 2, 1), 		array('Maqam Shawq Afza')),
array(array(1, 1, 1, 1, 1, 2, 1, 2, 1, 1), 		array('Raga Sindhi-Bhairavi')),
array(array(1, 2, 1, 1, 1, 1, 1, 1, 1, 2), 		array('Maqam Tarzanuyn')),
array(array(1, 1, 2, 1, 1, 1, 1, 2, 1, 1), 		array('Symmetrical Decatonic')),
array(array(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 	array('Twelve-tone Chromatic (1/11-comma)'))
);


foreach($scales as $scale) {
	$steps = $scale[0];
	$names = $scale[1];

	$root = 0;
	$tones = array();
	$tones[] = $root;
	foreach($steps as $step) {
		$root = $root + $step;
		$tones[] = $root;
	}

	$bits = 0;
	foreach($tones as $bit) {
		$bits += 2^$bit;
	}

	echo "\n";
	echo $bits . ' => array('. implode(',', $names) .'),';
}

